name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00AM UTC
    - cron: '30 8,10,19 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          ### content
          BLOCKS: =>
          CODE_LANG: HTML CSS Javascript C++ Python
          IGNORED_LANGUAGES: Markdown Git Gitignore
          SHOW_TIME: true 
          SHOW_TOTAL: true 
